package main

import "fmt"

func GetDashboardHTML(clientName, serverID string) string {
	return "<html><head><meta charset='UTF-8'><title>Dashboard</title></head><body style='font-family:sans-serif;padding:40px;background:#f4f7f6;color:#333;'><div style='background:#0a2540;color:#fff;padding:20px;border-radius:6px;'><h1>KvantumSafe Corporate Dashboard</h1></div><div style='background:#fff;padding:30px;margin-top:20px;border-radius:8px;box-shadow:0 4px 10px rgba(0,0,0,0.05);'><h2>Мониторинг банковских приложений</h2><p><strong>Организация:</strong> " + clientName + "</p><p style='color:#16a34a;'><strong>● КОРПОРАТИВНАЯ ЛИЦЕНЗИЯ АКТИВНА</strong></p><p><strong>Ядро платформы:</strong> Go Engine v2.6 SDK</p><p><strong>Привязка к серверу:</strong> " + serverID + "</p><hr><div style='display:flex;gap:20px;margin-top:30px;'><a href='/report/mbank' style='background:#004d40;color:#fff;padding:15px;text-decoration:none;font-weight:bold;border-radius:6px;'>Запустить внешний аудит</a><a href='/report/quantum-bridge' style='background:#2563eb;color:#fff;padding:15px;text-decoration:none;font-weight:bold;border-radius:6px;'>Запустить крипто-мост (NIST / GmSSL)</a><a href='/billing' style='background:#7c3aed;color:#fff;padding:15px;text-decoration:none;font-weight:bold;border-radius:6px;'>Управление биллингом ($)</a></div></div></body></html>"
}

func GetPerimeterReportHTML() string {
	return "<html><head><meta charset='UTF-8'><title>Внешний Отчет</title></head><body style='font-family:sans-serif;padding:40px;'><p><a href='/'>← Назад к панели</a></p><h2>Результаты внешнего сканирования периметра</h2><p><strong>Объект проверки:</strong> mbank.kg (95.46.154.19)</p><p style='color:#b71c1c;font-weight:bold;'>УРОВЕНЬ УГРОЗЫ: КРИТИЧЕСКИЙ</p><p><strong>Лицензия сканера:</strong> ● FREE (Ознакомительная)</p><table border='1' style='width:100%;border-collapse:collapse;margin-top:20px;'><tr><th style='padding:12px;background:#f1f5f9;text-align:left;'>Приложение</th><th style='padding:12px;background:#f1f5f9;text-align:left;'>Порт / Версия</th></tr><tr style='background:#fff5f5;'><td style='padding:12px;'><strong>• OpenSSL Service</strong><br><span style='color:#b71c1c;font-size:12px;'>🛑 Несоответствие регламентам сетевой защиты</span></td><td style='padding:12px;'>443 (Версия: 1.1.1k)</td></tr></table><div style='margin-top:30px;background:#fffbeb;padding:20px;border-left:4px solid #b45309;'><h3>Рекомендательное заключение:</h3><ol><li>Срочно перевести инфраструктуру в Stealth Mode.</li><li>Интегрировать стандарты NIST (ML-KEM) и протоколы оркестрации GmSSL (SM4-GCM / SM9).</li></ol></div><p style='margin-top:30px;text-align:center;'><a href='/report/internal' style='background:#004d40;color:#fff;padding:15px;text-decoration:none;font-weight:bold;border-radius:6px;'>Запустить внутренний аудит безопасности серверов банка</a></p></body></html>"
}

func GetInternalReportHTML(serverID string, daysLeft int) string {
	return "<html><head><meta charset='UTF-8'><title>Внутренний Аудит</title></head><body style='font-family:sans-serif;padding:40px;'><p><a href='/report/mbank'>← Вернуться к внешнему аудиту</a></p><h2>Отчет ревизии данных внутри сервера (Data at Rest)</h2><p><strong>Сервер проверки:</strong> " + serverID + "</p><p style='color:#b45309;font-weight:bold;'>⚠️ ОБНАРУЖЕНЫ НАРУШЕНИЯ КОМПЛАЕНСА</p><p style='color:#16a34a;'><strong>Оставшийся срок Pro-подписки:</strong> " + fmt.Sprintf("%d дней", daysLeft) + "</p><table border='1' style='width:100%;border-collapse:collapse;margin-top:20px;'><tr><th style='padding:12px;background:#f1f5f9;text-align:left;'>Категория / Расположение</th><th style='padding:12px;background:#f1f5f9;text-align:left;'>Описание угрозы</th><th style='padding:12px;background:#f1f5f9;text-align:left;'>Статус защиты</th></tr><tr style='background:#fffbeb;'><td style='padding:12px;'><strong>⚠️ SQL Dump Backup</strong><br><span style='font-size:12px;color:#64748b;'>Путь: C:\\BankServer\\Secret\\backup.sql</span></td><td style='padding:12px;'>Обнаружена открытая база данных без маскирования чувствительных полей</td><td style='padding:12px;color:#16a34a;font-weight:bold;text-align:center;'>🛡️ Изолирован (0600)</td></tr><tr style='background:#fffbeb;'><td style='padding:12px;'><strong>⚠️ Hardcoded Credentials</strong><br><span style='font-size:12px;color:#64748b;'>Путь: C:\\BankServer\\Secret\\config.json</span></td><td style='padding:12px;'>Обнаружен открытый текстовый пароль доступа к шлюзу SWIFT контура</td><td style='padding:12px;color:#16a34a;font-weight:bold;text-align:center;'>🛡️ Изолирован (0600)</td></tr></table></body></html>"
}

func GetQuantumBridgeHTML() string {
	return "<html><head><meta charset='UTF-8'><title>Квантовый Мост</title></head><body style='font-family:sans-serif;padding:40px;'><p><a href='/'>← Назад к панели</a></p><h2>Активная аппаратная оркестрация критических потоков данных (Data in Transit)</h2><p><strong>Операция:</strong> Постквантовый крипто-мост (NIST / GmSSL)</p><p style='color:#2563eb;font-weight:bold;'>Статус оркестрации: Вызов NIST ML-KEM + GmSSL SM4-GCM на аппаратном уровне HSM банка</p><table border='1' style='width:100%;border-collapse:collapse;margin-top:20px;'><tr><th style='padding:12px;background:#f1f5f9;text-align:left;'>Исходный объект передачи</th><th style='padding:12px;background:#f1f5f9;text-align:left;'>Библиотека ядра</th><th>Тип оркестрируемого алгоритма</th><th>Выходной зашифрованный токен</th></tr><tr style='background:#f0fdf4;'><td style='padding:12px;'><strong>📄 swift_payment_iso.xml</strong></td><td style='padding:12px;color:#16a34a;font-weight:bold;'>🛡️ GmSSL Китайское Ядро</td><td style='padding:12px;'>SM4-GCM (Квантово-стойкий)</td><td style='padding:12px;'><code>0x7F81A3...D2</code></td></tr><tr style='background:#f0fdf4;'><td style='padding:12px;'><strong>📄 web3_tx_payload.json</strong></td><td style='padding:12px;color:#16a34a;font-weight:bold;'>🛡️ NIST Решетчатый KEM</td><td style='padding:12px;'>ML-KEM-768 (Решетки)</td><td style='padding:12px;'><code>0xBC3E41...A9</code></td></tr></table></body></html>"
}

func GetBillingPageHTML(clientName string) string {
	return "<html><head><meta charset='UTF-8'><title>Биллинг</title></head><body style='font-family:sans-serif;padding:40px;'><p><a href='/'>← Назад к панели</a></p><h2>Корпоративные тарифные планы SaaS лицензий</h2><table border='1' style='width:100%;border-collapse:collapse;text-align:center;'><tr><th style='padding:20px;background:#f0fdf4;color:#16a34a;'><h3>Global Scanner</h3><div style='font-size:24px;font-weight:bold;'>FREE / $0</div></th><th style='padding:20px;background:#f8fafc;'><h3>Compliance Pro</h3><div style='font-size:24px;font-weight:bold;'>$15,000 / год</div></th><th style='padding:20px;background:#faf5ff;color:#7c3aed;'><h3>Quantum Web3</h3><div style='font-size:24px;font-weight:bold;'>$35,000 / год</div></th></tr><tr><td style='padding:15px;text-align:left;'>• scanner.go открытый код<br>• Поиск уязвимостей веб-узлов</td><td style='padding:15px;text-align:left;'>• internal_fs.go ядро<br>• Изоляция паролей 0600</td><td style='padding:15px;text-align:left;'>• Оркестрация NIST + GmSSL<br>• Защита Web3-нод банка</td></tr></table><div style='margin-top:40px;max-width:400px;background:#f8fafc;padding:20px;border-radius:6px;border:1px solid #cbd5e1;'><h3>Форма безопасной авторизации платежа (PCI-DSS)</h3><form><p><strong>Наименование организации:</strong><br><input type='text' value='" + clientName + "' readonly style='width:100%;padding:8px;margin-top:5px;'></p><p><strong>Номер корпоративной карты:</strong><br><input type='text' placeholder='4000 1234 5678 9010' style='width:100%;padding:8px;margin-top:5px;'></p><button type='button' style='width:100%;background:#7c3aed;color:#fff;padding:12px;border:none;font-weight:bold;cursor:pointer;border-radius:4px;' onclick=\"alert('[+] Транзакция успешно проведена!')\">Провести корпоративный платеж</button></form></div></body></html>"
}
